package br.com.margel.updater.model;

public enum UpdateStep {

	CHECKING_DESKTOP_SHORTCUT,
	UPDATING_DESKTOP_SHORTCUT,
	INSTALLATION_FINISHED,
	UPDATE_FINISHED,
	LOOKING_FOR_UPDATES_ONLINE,
	DOWNLOADING_UPDATE,
	DOWNLOAD_SUCCESS,
	DOWNLOAD_ERROR
	;
}
